# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0009_corte_tabla_unica"),
        ("facturacion", "0002_alter_facturaagrupacion_codigo_sic_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratofactura",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrato_factura_por_contrato_id",
                to="contratos.contrato",
            ),
        ),
    ]
