# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0009_corte_tabla_unica"),
        ("fronteras", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratofrontera",
            name="contrato_servicio",
            field=models.ForeignKey(
                db_column="contrato_servicio_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrato_frontera_por_contrato_servicio_id",
                to="contratos.contrato",
            ),
        ),
    ]
