# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0009_corte_tabla_unica"),
        ("mercado_xm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asicsolicitud",
            name="contrato_ppa",
            field=models.ForeignKey(
                blank=True,
                db_column="contrato_ppa_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="asic_solicitudes_por_contrato_ppa_id",
                to="contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="clasificacionenergiamensual",
            name="contrato_ppa",
            field=models.ForeignKey(
                blank=True,
                db_column="contrato_ppa_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clasificacion_energia_mensual_por_contrato_ppa_id",
                to="contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="cumplimientomensual",
            name="contrato_ppa",
            field=models.ForeignKey(
                db_column="contrato_ppa_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cumplimiento_mensual_por_contrato_ppa_id",
                to="contratos.contrato",
            ),
        ),
    ]
