# Generated by Django 6.0.8 on 2026-09-17 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0001_initial'),
        ('proyectos', '0007_quitar_indice_solarview_repetido'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_corte', models.DateField(db_index=True)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('codigo', models.CharField(max_length=40)),
                ('contrato', models.CharField(blank=True, max_length=200, null=True)),
                ('comprador', models.CharField(blank=True, max_length=10, null=True)),
                ('deficit_mwh', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('pct', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='garantia_contrato_por_proyecto_id', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'garantia_contrato',
                'unique_together': {('fecha_corte', 'anio', 'mes', 'codigo')},
            },
        ),
    ]
