# Generated by Django 6.0.8 on 2026-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garantias', '0002_garantiacontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantiacontrato',
            name='comprador',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
