# Generated by Django 6.0.8 on 2026-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteenergiaconsumo',
            name='curva_cgm_referencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteenergiageneracion',
            name='curva_cgm_referencia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
