# Generated by Django 6.0.8 on 2026-09-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_gestionregistro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='srv_rec',
        ),
    ]
