# Generated by Django 6.0.8 on 2026-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronteras', '0002_initial'),
        ('proyectos', '0005_potencia_ac_una_sola_columna'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_tsf__isnull', False), ('deleted_at__isnull', True)), fields=('codigo_tsf',), name='uq_proyectos_codigo_tsf_vivo'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('origina_code__isnull', False)), fields=('origina_code',), name='uq_proyectos_origina_code_vivo'),
        ),
    ]
