# Generated by Django 6.0.8 on 2026-09-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_corte_tabla_unica"),
        ("proyectos", "0008_quitar_comunidad_del_proyecto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inversionista",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inversionistas_por_cliente_id",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "inversionistas",
            },
        ),
        migrations.AddField(
            model_name="proyectoinversionista",
            name="inversionista",
            field=models.ForeignKey(
                blank=True,
                db_column="inversionista_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="proyecto_inversionistas_por_inversionista_id",
                to="proyectos.inversionista",
            ),
        ),
        migrations.AddConstraint(
            model_name="inversionista",
            constraint=models.UniqueConstraint(
                fields=("cliente",), name="uq_inversionistas_cliente"
            ),
        ),
    ]
