# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arriendos", "0003_initial"),
        ("contratos", "0008_contratos_unificados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrarrendador",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arr_arrendador_por_contrato_id",
                to="contratos.contrato",
            ),
        ),
    ]
