# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_documento_cedula_ciudadania"),
        ("contratos", "0008_contratos_unificados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientedocumentocomercial",
            name="contrato_servicio",
            field=models.ForeignKey(
                blank=True,
                db_column="contrato_servicio_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente_documentos_comerciales_por_contrato_servicio_id",
                to="contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="clientedocumentocomercial",
            name="ppa_contrato",
            field=models.ForeignKey(
                blank=True,
                db_column="ppa_contrato_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos_comerciales",
                to="contratos.contrato",
            ),
        ),
    ]
