"""Corte (deploy 2, plan `docs/refactor/08-plan-django-contratos.md`): SOLO estado.

Le dice a Django que las llaves de esta app apuntan a `contratos`. No ejecuta SQL: todo el trabajo sobre la base lo hizo
`contratos/0009_corte_bd` en una sola transacción (llaves foráneas y reescritura de
ids). Por eso las operaciones van dentro de `SeparateDatabaseAndState` sin
`database_operations`: tal como las genera Django, cambiarían las llaves por su cuenta
o borrarían tablas viejas que se conservan hasta el deploy 3.
"""
# Generated by Django 6.0.8 on 2026-10-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_documento_cedula_ciudadania'),
        ('contratos', '0009_corte_bd'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='clientedocumentocomercial',
                    name='contrato_servicio',
                    field=models.ForeignKey(blank=True, db_column='contrato_servicio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_documentos_comerciales_por_contrato_servicio_id', to='contratos.contrato'),
                ),
                migrations.AlterField(
                    model_name='clientedocumentocomercial',
                    name='ppa_contrato',
                    field=models.ForeignKey(blank=True, db_column='ppa_contrato_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_comerciales', to='contratos.contrato'),
                ),
            ],
        ),
    ]
