# Generated by Django 6.0.8 on 2026-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_informeguardado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeguardado',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
