# Generated by Django 6.0.8 on 2026-09-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_alter_fallaintervalo_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallaseguimiento',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
