# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0009_corte_tabla_unica"),
        ("monitoreo", "0006_eliminar_mantenimientos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="ppa",
            field=models.ForeignKey(
                db_column="ppa_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas_por_ppa_id",
                to="contratos.contrato",
            ),
        ),
    ]
