# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0009_corte_tabla_unica"),
        ("om", "0003_alter_omseleccionmensual_valor_facturado_congelado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="omdocumentoproyecto",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="om_documento_proyecto_por_contrato_id",
                to="contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="ompaginasinmatch",
            name="contrato_id_asignado",
            field=models.ForeignKey(
                blank=True,
                db_column="contrato_id_asignado",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="om_pagina_sin_match_por_contrato_id_asignado",
                to="contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="omseleccionmensual",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="om_seleccion_mensual_por_contrato_id",
                to="contratos.contrato",
            ),
        ),
    ]
