"""Corte (deploy 2, plan `docs/refactor/08-plan-django-contratos.md`): SOLO estado.

Le dice a Django que las llaves de esta app apuntan a `contratos`. No ejecuta SQL: todo el trabajo sobre la base lo hizo
`contratos/0009_corte_bd` en una sola transacción (llaves foráneas y reescritura de
ids). Por eso las operaciones van dentro de `SeparateDatabaseAndState` sin
`database_operations`: tal como las genera Django, cambiarían las llaves por su cuenta
o borrarían tablas viejas que se conservan hasta el deploy 3.
"""
# Generated by Django 6.0.8 on 2026-10-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_corte_estado'),
        ('om', '0003_alter_omseleccionmensual_valor_facturado_congelado_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='omdocumentoproyecto',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='om_documento_proyecto_por_contrato_id', to='contratos.contrato'),
                ),
                migrations.AlterField(
                    model_name='ompaginasinmatch',
                    name='contrato_id_asignado',
                    field=models.ForeignKey(blank=True, db_column='contrato_id_asignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='om_pagina_sin_match_por_contrato_id_asignado', to='contratos.contrato'),
                ),
                migrations.AlterField(
                    model_name='omseleccionmensual',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='om_seleccion_mensual_por_contrato_id', to='contratos.contrato'),
                ),
            ],
        ),
    ]
