"""Corte (deploy 2, plan `docs/refactor/08-plan-django-contratos.md`): SOLO estado.

Le dice a Django que `PpaContrato` y `PpaContratoProyecto` pasan a ser fachadas sobre `contratos` y `contrato_proyectos`, y que las tarifas y compromisos apuntan a `contratos`; `ppa_contratos` y `ppa_contrato_proyectos` quedan en la base, sin modelo. No ejecuta SQL: todo el trabajo sobre la base lo hizo
`contratos/0009_corte_bd` en una sola transacción (llaves foráneas y reescritura de
ids). Por eso las operaciones van dentro de `SeparateDatabaseAndState` sin
`database_operations`: tal como las genera Django, cambiarían las llaves por su cuenta
o borrarían tablas viejas que se conservan hasta el deploy 3.
"""
# Generated by Django 6.0.8 on 2026-10-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_corte_estado'),
        ('comercial', '0006_corte_estado'),
        ('contratos', '0010_corte_estado'),
        ('mercado_xm', '0002_corte_estado'),
        ('monitoreo', '0008_corte_estado'),
        ('ppa', '0002_fecha_entrada_comunidad'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='ppatarifa',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='contratos.contrato'),
                ),
                migrations.RemoveField(
                    model_name='ppacontratoproyecto',
                    name='contrato',
                ),
                migrations.AlterField(
                    model_name='ppacompromisoenergia',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='contratos.contrato'),
                ),
                migrations.RemoveField(
                    model_name='ppacontratoproyecto',
                    name='proyecto',
                ),
                migrations.DeleteModel(
                    name='PpaContrato',
                ),
                migrations.DeleteModel(
                    name='PpaContratoProyecto',
                ),
                migrations.CreateModel(
                    name='PpaContrato',
                    fields=[
                    ],
                    options={
                        'verbose_name': 'Contrato PPA',
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('contratos.contrato',),
                ),
                migrations.CreateModel(
                    name='PpaContratoProyecto',
                    fields=[
                    ],
                    options={
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('contratos.contratoproyecto',),
                ),
            ],
        ),
    ]
