# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_corte_tabla_unica"),
        ("comercial", "0006_corte_tabla_unica"),
        ("contratos", "0009_corte_tabla_unica"),
        ("mercado_xm", "0002_corte_tabla_unica"),
        ("monitoreo", "0007_corte_tabla_unica"),
        ("ppa", "0002_fecha_entrada_comunidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppatarifa",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifas_ppa",
                to="contratos.contrato",
            ),
        ),
        migrations.RemoveField(
            model_name="ppacontratoproyecto",
            name="contrato",
        ),
        migrations.AlterField(
            model_name="ppacompromisoenergia",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compromisos",
                to="contratos.contrato",
            ),
        ),
        migrations.RemoveField(
            model_name="ppacontratoproyecto",
            name="proyecto",
        ),
        migrations.DeleteModel(
            name="PpaContrato",
        ),
        migrations.DeleteModel(
            name="PpaContratoProyecto",
        ),
        migrations.CreateModel(
            name="PpaContrato",
            fields=[],
            options={
                "verbose_name": "Contrato PPA",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contratos.contrato",),
        ),
        migrations.CreateModel(
            name="PpaContratoProyecto",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contratos.contratoproyecto",),
        ),
    ]
