# Generated by Django 6.0.8 on 2026-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoservicio',
            name='rec_cantidad',
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='rec_precio_unitario',
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='rec_vintage',
        ),
        migrations.AlterField(
            model_name='contratoservicio',
            name='servicio_aplica',
            field=models.CharField(choices=[('representacion', 'representacion'), ('cgm', 'cgm'), ('mantenimiento', 'mantenimiento'), ('arriendo', 'arriendo'), ('internet', 'internet')], max_length=14),
        ),
    ]
