# Generated by Django 6.0.8 on 2026-09-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_remove_contratoservicio_rec_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoservicio',
            name='tiene_cgm',
        ),
    ]
