# Generated by Django 6.0.8 on 2026-09-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_remove_contratoservicio_tiene_cgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAniversario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aniversario', models.DateField()),
                ('dias_aviso', models.IntegerField()),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas_aniversario', to='contratos.contratoservicio')),
            ],
            options={
                'db_table': 'contrato_alertas_aniversario',
                'unique_together': {('contrato', 'aniversario', 'dias_aviso')},
            },
        ),
    ]
