# Generated by Django 6.0.8 on 2026-09-24 21:02

import apps.contratos.models
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_documento_cedula_ciudadania"),
        ("contratos", "0007_eliminar_pagos_servicio"),
        ("plataforma", "0003_alter_informeguardado_correo_enviado"),
        ("ppa", "0002_fecha_entrada_comunidad"),
        ("proyectos", "0008_quitar_comunidad_del_proyecto"),
    ]

    operations = [
        # DEBE ir primero, en ESTA misma migración: el EXCLUDE de contrato_tarifas usa
        # gist sobre (contrato_id, concepto, vigencia), y btree_gist no está instalada en
        # ninguna de las dos bases. Permiso verificado en Railway/PG 17.9 (D-24).
        # `CREATE EXTENSION IF NOT EXISTS` → idempotente. En backends != postgres
        # (SQLite de las pruebas) BtreeGistExtension es un no-op.
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("vencido", "Vencido"),
                            ("terminado", "Terminado"),
                            ("en_renovacion", "En renovación"),
                        ],
                        default="vigente",
                        max_length=13,
                    ),
                ),
                (
                    "numero_contrato",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "nombre_interno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_firma", models.DateField(blank=True, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "tarifa_base",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "periodicidad_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mensual", "Mensual"),
                            ("bimestral", "Bimestral"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "indice_indexacion",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("renovacion_automatica", models.BooleanField(default=False)),
                (
                    "comprador_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comprador_nit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "vendedor_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vendedor_nit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "contratante_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contratante_nit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "prestador_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prestador_nit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "inversionista_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "compraventa",
                    models.CharField(
                        blank=True,
                        choices=[("venta", "Venta"), ("compra", "Compra")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "periodo_indexacion_base",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "valor_indexacion_base",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "cantidad_minima_kwh_mes",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "cantidad_maxima_kwh_mes",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "periodicidad_facturacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tiempo_pago", models.IntegerField(blank=True, null=True)),
                (
                    "condiciones_pago",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "gescon_codigo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gescon_fecha_inicio", models.DateField(blank=True, null=True)),
                ("gescon_fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "gescon_precio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "gescon_cantidades_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("codigo_sic", models.CharField(blank=True, max_length=50, null=True)),
                ("es_comunidad_energetica", models.BooleanField(blank=True, null=True)),
                ("fecha_entrada_comunidad", models.DateField(blank=True, null=True)),
                (
                    "nombre_comunidad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cgm_codigo_sic",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("fecha_inicio_om", models.DateField(blank=True, null=True)),
                ("fecha_indexacion", models.DateField(blank=True, null=True)),
                ("responsable_iva", models.BooleanField(default=False)),
                ("estado_pago", models.CharField(blank=True, max_length=20, null=True)),
                ("portafolio", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "codigo_sun_factory",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nombre_proyecto_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ubicacion_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "ubicacion_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "plan_datos_gb",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("velocidad_mbps", models.IntegerField(blank=True, null=True)),
                (
                    "tipo_conexion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "linea_servicio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("id_router", models.CharField(blank=True, max_length=100, null=True)),
                ("numero_kit", models.CharField(blank=True, max_length=100, null=True)),
                ("latencia_ms", models.IntegerField(blank=True, null=True)),
                (
                    "wifi_seguridad",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wifi_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsable_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_unificados",
                        to="ppa.pparesponsable",
                    ),
                ),
            ],
            options={
                "db_table": "contratos",
            },
        ),
        migrations.CreateModel(
            name="ContratoParte",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("propietario", "Propietario"),
                            ("arrendador", "Arrendador"),
                            ("arrendatario", "Arrendatario"),
                            ("comprador", "Comprador"),
                            ("vendedor", "Vendedor"),
                            ("operador", "Operador"),
                            ("mantenedor", "Mantenedor"),
                            ("representante", "Representante"),
                        ],
                        max_length=13,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrato_partes",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partes",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "db_table": "contrato_partes",
            },
        ),
        migrations.CreateModel(
            name="ContratoProyecto",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "contrato_id",
                        "proyecto_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        db_column="proyecto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_unificados",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "db_table": "contrato_proyectos",
            },
        ),
        migrations.CreateModel(
            name="ContratoTarifa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "concepto",
                    models.CharField(
                        choices=[
                            ("administracion", "Administración"),
                            ("cgm", "CGM"),
                            ("representacion", "Representación"),
                            ("canon", "Canon"),
                            ("energia", "Energía"),
                        ],
                        max_length=14,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("porcentaje", "Porcentaje"),
                            ("cop_kwh", "COP/kWh"),
                            ("cop_mes", "COP/mes"),
                            ("cop_total", "COP total"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vigencia", django.contrib.postgres.fields.ranges.DateRangeField()),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("pactada", "Pactada"),
                            ("indexacion", "Indexación"),
                            ("renegociacion", "Renegociación"),
                            ("correccion", "Corrección"),
                            ("migracion", "Migración"),
                        ],
                        max_length=13,
                    ),
                ),
                ("indice", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "indice_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True)),
                ("anulada_en", models.DateTimeField(blank=True, null=True)),
                ("anulada_motivo", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anulada_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="anulada_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarifas_anuladas",
                        to="plataforma.usuario",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="registrado_por_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarifas_registradas",
                        to="plataforma.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "contrato_tarifas",
            },
        ),
        migrations.CreateModel(
            name="ContratoTipo",
            fields=[
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("representacion", "Representación"),
                            ("cgm", "CGM"),
                            ("compraventa_energia", "Compraventa de energía"),
                            ("arriendo", "Arriendo"),
                            ("operacion", "Operación"),
                            ("mantenimiento", "Mantenimiento"),
                            ("internet", "Internet"),
                        ],
                        max_length=19,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "contrato_id",
                        "tipo",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        db_column="contrato_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "db_table": "contrato_tipos",
            },
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_fin__isnull", True),
                    ("fecha_inicio__isnull", True),
                    ("fecha_fin__gte", models.F("fecha_inicio")),
                    _connector="OR",
                ),
                name="ck_contratos_fechas",
            ),
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tarifa_base__isnull", True),
                    ("tarifa_base__gte", 0),
                    _connector="OR",
                ),
                name="ck_contratos_tarifa",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratoparte",
            constraint=models.UniqueConstraint(
                fields=("contrato", "cliente", "rol"), name="uq_contrato_partes"
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gte", 0)), name="ck_contrato_tarifas_valor"
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=apps.contratos.models.PgCheckConstraint(
                condition=models.Q(("vigencia__isempty", False)),
                name="ck_contrato_tarifas_vigencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unidad", "porcentaje"), _negated=True),
                    ("valor__lte", 1),
                    _connector="OR",
                ),
                name="ck_contrato_tarifas_pct",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("origen", "indexacion"), ("indice__isnull", False)),
                    models.Q(
                        models.Q(("origen", "indexacion"), _negated=True),
                        ("indice__isnull", True),
                        ("indice_pct__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_contrato_tarifas_indice",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("origen", "migracion"), _negated=True),
                    ("nota__isnull", False),
                    _connector="OR",
                ),
                name="ck_contrato_tarifas_migracion",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("anulada_en__isnull", True), ("anulada_motivo__isnull", True)
                    ),
                    models.Q(
                        ("anulada_en__isnull", False), ("anulada_motivo__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_contrato_tarifas_anulada",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratotarifa",
            constraint=apps.contratos.models.PgExclusionConstraint(
                condition=models.Q(("anulada_en__isnull", True)),
                expressions=[("contrato", "="), ("concepto", "="), ("vigencia", "&&")],
                name="ex_contrato_tarifas_sin_solape",
            ),
        ),
    ]
