"""Deploy 1 del plan `docs/refactor/08-plan-django-contratos.md`: tablas nuevas, VACÍAS.

Crea `contratos`, `contrato_proyectos`, `servicios` y
`contratos_servicio_correspondencia`. No toca ninguna tabla existente y nadie las lee:
la app sigue usando `ppa_contratos` y `contratos_servicio`. Se llenan a mano con
`manage.py backfill_contratos_unificados` y entran en uso en el corte (deploy 2).

Rollback: revertir esta migración borra cuatro tablas sin datos que nada referencia.
"""
# Generated by Django 6.0.8 on 2026-10-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_documento_cedula_ciudadania'),
        ('contratos', '0007_eliminar_pagos_servicio'),
        ('ppa', '0002_fecha_entrada_comunidad'),
        ('proyectos', '0008_quitar_comunidad_del_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(choices=[('ppa', 'PPA'), ('representacion_cgm', 'Representación y CGM'), ('operacion', 'Operación')], max_length=20)),
                ('estado', models.CharField(choices=[('firmado', 'Firmado'), ('en_renovacion', 'En renovación'), ('terminado', 'Terminado')], default='firmado', max_length=13)),
                ('numero_contrato', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_codigo_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_interno', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_firma_contrato', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tarifa_base', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('periodicidad_pago', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10, null=True)),
                ('indice_indexacion', models.CharField(blank=True, max_length=60, null=True)),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('comprador_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('comprador_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('vendedor_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('contratante_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contratante_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('prestador_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('prestador_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('inversionista_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('venta', 'Venta'), ('compra', 'Compra')], max_length=20, null=True)),
                ('periodicidad_indexacion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_indexacion_base', models.CharField(blank=True, max_length=7, null=True)),
                ('valor_indexacion_base', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cantidad_minima_kwh_mes', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('cantidad_maxima_kwh_mes', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('periodicidad_facturacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_pago', models.IntegerField(blank=True, null=True)),
                ('condiciones_pago', models.CharField(blank=True, max_length=500, null=True)),
                ('gescon_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('gescon_fecha_inicio', models.DateField(blank=True, null=True)),
                ('gescon_fecha_fin', models.DateField(blank=True, null=True)),
                ('gescon_precio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('gescon_cantidades_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('codigo_sic', models.CharField(blank=True, max_length=50, null=True)),
                ('es_comunidad_energetica', models.BooleanField(blank=True, null=True)),
                ('fecha_entrada_comunidad', models.DateField(blank=True, null=True)),
                ('nombre_comunidad', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio_aplica', models.CharField(blank=True, choices=[('representacion', 'representacion'), ('cgm', 'cgm'), ('mantenimiento', 'mantenimiento'), ('arriendo', 'arriendo'), ('internet', 'internet')], max_length=14, null=True)),
                ('tarifa_admin', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('tarifa_cgm', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tarifa_representacion', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tarifa_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('indexacion_anual', models.JSONField(blank=True, null=True)),
                ('indexacion_mensual', models.JSONField(blank=True, null=True)),
                ('indexacion_cgm', models.JSONField(blank=True, null=True)),
                ('indexacion_representacion', models.JSONField(blank=True, null=True)),
                ('cgm_codigo_sic', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio_om', models.DateField(blank=True, null=True)),
                ('fecha_indexacion', models.DateField(blank=True, null=True)),
                ('responsable_iva', models.BooleanField(default=False)),
                ('estado_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('portafolio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sun_factory', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_proyecto_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('plan_datos_gb', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidad_mbps', models.IntegerField(blank=True, null=True)),
                ('tipo_conexion', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('id_router', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_kit', models.CharField(blank=True, max_length=100, null=True)),
                ('latencia_ms', models.IntegerField(blank=True, null=True)),
                ('wifi_seguridad', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comprador', models.ForeignKey(blank=True, db_column='comprador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.cliente')),
                ('contratante', models.ForeignKey(blank=True, db_column='contratante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.cliente')),
                ('inversionista', models.ForeignKey(blank=True, db_column='inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.cliente')),
                ('prestador', models.ForeignKey(blank=True, db_column='prestador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.cliente')),
                ('proyecto', models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyectos.proyecto')),
                ('responsable', models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ppa.pparesponsable')),
                ('vendedor', models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.cliente')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='ContratoProyecto',
            fields=[
                ('pk', models.CompositePrimaryKey('contrato_id', 'proyecto_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contratos.contrato')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'contrato_proyectos',
            },
        ),
        migrations.CreateModel(
            name='ContratoServicioCorrespondencia',
            fields=[
                ('id_viejo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contrato', models.OneToOneField(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contratos.contrato')),
            ],
            options={
                'db_table': 'contratos_servicio_correspondencia',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(choices=[('compra', 'Compra de energía'), ('venta', 'Venta de energía'), ('representacion', 'Representación'), ('cgm', 'CGM'), ('mantenimiento', 'Mantenimiento'), ('arriendo', 'Arriendo'), ('internet', 'Internet')], max_length=20)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contratos.contrato')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_contratos_fechas'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('tarifa_base__isnull', True), ('tarifa_base__gte', 0), _connector='OR'), name='ck_contratos_tarifa'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo', 'ppa'), ('servicio_aplica__isnull', True)), models.Q(('grupo', 'representacion_cgm'), ('servicio_aplica__in', ('representacion', 'cgm'))), models.Q(('grupo', 'operacion'), ('servicio_aplica__in', ('mantenimiento', 'arriendo', 'internet'))), _connector='OR'), name='ck_contratos_grupo'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('contrato', 'servicio'), name='uq_servicios_contrato_servicio'),
        ),
    ]
