# Generated by Django 6.0.8 on 2026-09-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0008_contratos_unificados"),
        ("proyectos", "0008_quitar_comunidad_del_proyecto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratoservicio",
            name="contratante",
        ),
        migrations.RemoveField(
            model_name="contratoservicio",
            name="inversionista",
        ),
        migrations.RemoveField(
            model_name="contratoservicio",
            name="prestador",
        ),
        migrations.RemoveField(
            model_name="contratoservicio",
            name="proyecto",
        ),
        migrations.AlterField(
            model_name="alertaaniversario",
            name="contrato",
            field=models.ForeignKey(
                db_column="contrato_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas_aniversario",
                to="contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("firmado", "Firmado"),
                    ("en_renovacion", "En renovación"),
                    ("terminado", "Terminado"),
                ],
                default="firmado",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="contratoproyecto",
            name="proyecto",
            field=models.ForeignKey(
                db_column="proyecto_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos_ppa",
                to="proyectos.proyecto",
            ),
        ),
    ]
