# Generated by Django 6.0.8 on 2026-09-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arriendos", "0004_corte_tabla_unica"),
        ("clientes", "0005_corte_tabla_unica"),
        ("comercial", "0006_corte_tabla_unica"),
        ("contratos", "0009_corte_tabla_unica"),
        ("facturacion", "0003_corte_tabla_unica"),
        ("fronteras", "0003_corte_tabla_unica"),
        ("om", "0004_corte_tabla_unica"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContratoServicio",
        ),
        migrations.CreateModel(
            name="ContratoServicio",
            fields=[],
            options={
                "verbose_name": "Contrato de servicio",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contratos.contrato",),
        ),
    ]
