"""Corte (deploy 2, plan `docs/refactor/08-plan-django-contratos.md`): SOLO estado.

Le dice a Django que las tablas nuevas tienen sus nombres de relación definitivos y que `AlertaAniversario` apunta a `contratos`. No ejecuta SQL: todo el trabajo sobre la base lo hizo
`contratos/0009_corte_bd` en una sola transacción (llaves foráneas y reescritura de
ids). Por eso las operaciones van dentro de `SeparateDatabaseAndState` sin
`database_operations`: tal como las genera Django, cambiarían las llaves por su cuenta
o borrarían tablas viejas que se conservan hasta el deploy 3.
"""
# Generated by Django 6.0.8 on 2026-10-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_corte_estado'),
        ('contratos', '0009_corte_bd'),
        ('ppa', '0002_fecha_entrada_comunidad'),
        ('proyectos', '0008_quitar_comunidad_del_proyecto'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='contratoservicio',
                    name='contratante',
                ),
                migrations.RemoveField(
                    model_name='contratoservicio',
                    name='inversionista',
                ),
                migrations.RemoveField(
                    model_name='contratoservicio',
                    name='prestador',
                ),
                migrations.RemoveField(
                    model_name='contratoservicio',
                    name='proyecto',
                ),
                migrations.AlterField(
                    model_name='alertaaniversario',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas_aniversario', to='contratos.contrato'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='comprador',
                    field=models.ForeignKey(blank=True, db_column='comprador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppa_contratos_por_comprador_id', to='clientes.cliente'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='contratante',
                    field=models.ForeignKey(blank=True, db_column='contratante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicio_por_contratante_id', to='clientes.cliente'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='inversionista',
                    field=models.ForeignKey(blank=True, db_column='inversionista_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicio_por_inversionista_id', to='clientes.cliente'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='prestador',
                    field=models.ForeignKey(blank=True, db_column='prestador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_servicio_por_prestador_id', to='clientes.cliente'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='proyecto',
                    field=models.ForeignKey(blank=True, db_column='proyecto_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos_servicio_por_proyecto_id', to='proyectos.proyecto'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='responsable',
                    field=models.ForeignKey(blank=True, db_column='responsable_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='ppa.pparesponsable'),
                ),
                migrations.AlterField(
                    model_name='contrato',
                    name='vendedor',
                    field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppa_contratos_por_vendedor_id', to='clientes.cliente'),
                ),
                migrations.AlterField(
                    model_name='contratoproyecto',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_vinculados', to='contratos.contrato'),
                ),
                migrations.AlterField(
                    model_name='contratoproyecto',
                    name='proyecto',
                    field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_ppa', to='proyectos.proyecto'),
                ),
                migrations.AlterField(
                    model_name='contratoserviciocorrespondencia',
                    name='contrato',
                    field=models.OneToOneField(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_servicio', to='contratos.contrato'),
                ),
                migrations.AlterField(
                    model_name='servicio',
                    name='contrato',
                    field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='contratos.contrato'),
                ),
            ],
        ),
    ]
