# Generated by Django 6.0.8 on 2026-09-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_corte_tabla_unica"),
        ("contratos", "0010_corte_tabla_unica"),
        ("ppa", "0003_corte_tabla_unica"),
        ("proyectos", "0008_quitar_comunidad_del_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="comprador",
            field=models.ForeignKey(
                blank=True,
                db_column="comprador_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ppa_contratos_por_comprador_id",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="contratante",
            field=models.ForeignKey(
                blank=True,
                db_column="contratante_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_servicio_por_contratante_id",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="inversionista",
            field=models.ForeignKey(
                blank=True,
                db_column="inversionista_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_servicio_por_inversionista_id",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="prestador",
            field=models.ForeignKey(
                blank=True,
                db_column="prestador_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_servicio_por_prestador_id",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                db_column="proyecto_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="contratos_servicio_por_proyecto_id",
                to="proyectos.proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                db_column="responsable_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos",
                to="ppa.pparesponsable",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                db_column="vendedor_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ppa_contratos_por_vendedor_id",
                to="clientes.cliente",
            ),
        ),
    ]
