"""Corte (deploy 2, plan `docs/refactor/08-plan-django-contratos.md`): SOLO estado.

Le dice a Django que `ContratoServicio` pasa a ser una fachada (proxy) sobre `contratos`; la tabla `contratos_servicio` queda en la base, sin modelo. No ejecuta SQL: todo el trabajo sobre la base lo hizo
`contratos/0009_corte_bd` en una sola transacción (llaves foráneas y reescritura de
ids). Por eso las operaciones van dentro de `SeparateDatabaseAndState` sin
`database_operations`: tal como las genera Django, cambiarían las llaves por su cuenta
o borrarían tablas viejas que se conservan hasta el deploy 3.
"""
# Generated by Django 6.0.8 on 2026-10-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0005_corte_estado'),
        ('clientes', '0005_corte_estado'),
        ('comercial', '0006_corte_estado'),
        ('contratos', '0010_corte_estado'),
        ('facturacion', '0004_corte_estado'),
        ('fronteras', '0003_corte_estado'),
        ('om', '0004_corte_estado'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='ContratoServicio',
                ),
                migrations.CreateModel(
                    name='ContratoServicio',
                    fields=[
                    ],
                    options={
                        'verbose_name': 'Contrato de servicio',
                        'proxy': True,
                        'indexes': [],
                        'constraints': [],
                    },
                    bases=('contratos.contrato',),
                ),
            ],
        ),
    ]
