# Generated by Django 6.0.8 on 2026-10-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_corte_estado'),
        ('contratos', '0011_corte_fachada_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoParte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('contratante', 'Contratante'), ('prestador', 'Prestador')], max_length=20)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='partes_de_contratos', to='clientes.cliente')),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='contratos.contrato')),
            ],
            options={
                'db_table': 'contrato_partes',
                'indexes': [models.Index(fields=['cliente', 'rol'], name='ix_contrato_partes_cliente')],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'rol', 'cliente'), name='uq_contrato_partes')],
            },
        ),
    ]
