# Generated by Django 6.0.8 on 2026-09-25 21:38

import apps.contratos.models
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0011_restaurar_related_names"),
        ("proyectos", "0008_quitar_comunidad_del_proyecto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "servicios",
            },
        ),
        migrations.CreateModel(
            name="ServicioPlantilla",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                (
                    "unidad_default",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("porcentaje", "Porcentaje"),
                            ("cop_kwh", "COP/kWh"),
                            ("cop_mes", "COP/mes"),
                            ("cop_total", "COP total"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "servicio_plantillas",
            },
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("valor", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("porcentaje", "Porcentaje"),
                            ("cop_kwh", "COP/kWh"),
                            ("cop_mes", "COP/mes"),
                            ("cop_total", "COP total"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vigencia", django.contrib.postgres.fields.ranges.DateRangeField()),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("pactada", "Pactada"),
                            ("indexacion", "Indexación"),
                            ("renegociacion", "Renegociación"),
                            ("correccion", "Corrección"),
                            ("migracion", "Migración"),
                        ],
                        max_length=13,
                    ),
                ),
                ("indice", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "indice_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True)),
                ("anulada_en", models.DateTimeField(blank=True, null=True)),
                ("anulada_motivo", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tarifas",
            },
        ),
        migrations.CreateModel(
            name="TarifaPlantilla",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=120)),
                ("valor", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("porcentaje", "Porcentaje"),
                            ("cop_kwh", "COP/kWh"),
                            ("cop_mes", "COP/mes"),
                            ("cop_total", "COP total"),
                        ],
                        max_length=10,
                    ),
                ),
                ("indice", models.CharField(blank=True, max_length=20, null=True)),
                ("anio", models.IntegerField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tarifa_plantillas",
            },
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ck_contrato_tarifas_valor",
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ck_contrato_tarifas_vigencia",
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ck_contrato_tarifas_pct",
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ck_contrato_tarifas_indice",
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ck_contrato_tarifas_migracion",
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ck_contrato_tarifas_anulada",
        ),
        migrations.RemoveConstraint(
            model_name="contratotarifa",
            name="ex_contrato_tarifas_sin_solape",
        ),
        migrations.RemoveField(
            model_name="contratotipo",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="contratoproyecto",
            name="pk",
        ),
        migrations.RemoveField(
            model_name="contratoproyecto",
            name="proyecto",
        ),
        migrations.AddField(
            model_name="contratoproyecto",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="contratoproyecto",
            name="proyecto_inversionista",
            field=models.ForeignKey(
                db_column="proyecto_inversionista_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contrato_proyectos",
                to="proyectos.proyectoinversionista",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="contratoproyecto",
            constraint=models.UniqueConstraint(
                fields=("contrato", "proyecto_inversionista"),
                name="uq_contrato_proyectos",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="contrato_proyecto",
            field=models.ForeignKey(
                db_column="contrato_proyecto_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios",
                to="contratos.contratoproyecto",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="servicio_plantilla",
            field=models.ForeignKey(
                db_column="servicio_plantilla_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servicios",
                to="contratos.servicioplantilla",
            ),
        ),
        migrations.AddField(
            model_name="tarifa",
            name="anulada_por",
            field=models.ForeignKey(
                blank=True,
                db_column="anulada_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarifas_srv_anuladas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tarifa",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                db_column="registrado_por_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarifas_srv_registradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tarifa",
            name="servicio",
            field=models.ForeignKey(
                db_column="servicio_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifas",
                to="contratos.servicio",
            ),
        ),
        migrations.AddField(
            model_name="tarifaplantilla",
            name="servicio_plantilla",
            field=models.ForeignKey(
                db_column="servicio_plantilla_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarifas_plantilla",
                to="contratos.servicioplantilla",
            ),
        ),
        migrations.AddField(
            model_name="tarifa",
            name="tarifa_plantilla_origen",
            field=models.ForeignKey(
                blank=True,
                db_column="tarifa_plantilla_origen_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarifas_instanciadas",
                to="contratos.tarifaplantilla",
            ),
        ),
        migrations.RemoveField(
            model_name="contratotarifa",
            name="anulada_por",
        ),
        migrations.RemoveField(
            model_name="contratotarifa",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="contratotarifa",
            name="registrado_por",
        ),
        migrations.DeleteModel(
            name="ContratoTipo",
        ),
        migrations.AddConstraint(
            model_name="servicio",
            constraint=models.UniqueConstraint(
                fields=("contrato_proyecto", "servicio_plantilla"),
                name="uq_servicios_contrato_proyecto_plantilla",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifaplantilla",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gte", 0)), name="ck_tarifa_plantillas_valor"
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifaplantilla",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unidad", "porcentaje"), _negated=True),
                    ("valor__lte", 1),
                    _connector="OR",
                ),
                name="ck_tarifa_plantillas_pct",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gte", 0)), name="ck_tarifas_valor"
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=apps.contratos.models.PgCheckConstraint(
                condition=models.Q(("vigencia__isempty", False)),
                name="ck_tarifas_vigencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unidad", "porcentaje"), _negated=True),
                    ("valor__lte", 1),
                    _connector="OR",
                ),
                name="ck_tarifas_pct",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("origen", "indexacion"), ("indice__isnull", False)),
                    models.Q(
                        models.Q(("origen", "indexacion"), _negated=True),
                        ("indice__isnull", True),
                        ("indice_pct__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_tarifas_indice",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("origen", "migracion"), _negated=True),
                    ("nota__isnull", False),
                    _connector="OR",
                ),
                name="ck_tarifas_migracion",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("anulada_en__isnull", True), ("anulada_motivo__isnull", True)
                    ),
                    models.Q(
                        ("anulada_en__isnull", False), ("anulada_motivo__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_tarifas_anulada",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=apps.contratos.models.PgExclusionConstraint(
                condition=models.Q(("anulada_en__isnull", True)),
                expressions=[("servicio", "="), ("vigencia", "&&")],
                name="ex_tarifas_sin_solape",
            ),
        ),
        migrations.DeleteModel(
            name="ContratoTarifa",
        ),
    ]
