# Generated by Django 6.0.8 on 2026-09-04 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadOferta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('servicios_operacionales', 'servicios_operacionales'), ('compra_energia', 'compra_energia'), ('comunidad_energetica', 'comunidad_energetica')], max_length=23)),
                ('planta_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_oferta', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('precio_detalle', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('oportunidad', 'oportunidad'), ('oferta', 'oferta'), ('contrato', 'contrato'), ('firmado', 'firmado'), ('operando', 'operando'), ('terminado', 'terminado'), ('declinado', 'declinado')], default='oportunidad', max_length=11)),
                ('estado_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(choices=[('pendiente', 'pendiente'), ('aceptado', 'aceptado'), ('declinado', 'declinado')], default='pendiente', max_length=9)),
                ('etapa_texto', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_oferta', models.DateField(blank=True, null=True)),
                ('fecha_tentativa_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_tentativa', models.DateField(blank=True, null=True)),
                ('contrato_firmado', models.CharField(blank=True, max_length=150, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('seguimientos', models.IntegerField(default=0)),
                ('fecha_ultima_respuesta', models.DateField(blank=True, null=True)),
                ('documento_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('energia_promedio_kwh_mes', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oportunidad_ofertas',
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('oportunidad', 'oportunidad'), ('oferta', 'oferta'), ('contrato', 'contrato'), ('firmado', 'firmado'), ('operando', 'operando'), ('terminado', 'terminado'), ('declinado', 'declinado')], default='oportunidad', max_length=11)),
                ('estado_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_oferta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_tentativa_inicio_representacion', models.DateField(blank=True, null=True)),
                ('fecha_tentativa_inicio_compra_energia', models.DateField(blank=True, null=True)),
                ('fecha_estimada_firma', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('es_migrada', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidades_por_cliente_id', to='clientes.cliente')),
                ('creado_por_usuario', models.ForeignKey(blank=True, db_column='creado_por_usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidades_por_creado_por_usuario_id', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'oportunidades',
            },
        ),
        migrations.CreateModel(
            name='OportunidadEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('oportunidad', models.ForeignKey(db_column='oportunidad_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidad_estado_historial_por_oportunidad_id', to='comercial.oportunidad')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidad_estado_historial_por_usuario_id', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'oportunidad_estado_historial',
            },
        ),
        migrations.CreateModel(
            name='OportunidadGestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('llamada', 'llamada'), ('correo', 'correo'), ('reunion', 'reunion'), ('whatsapp', 'whatsapp'), ('nota', 'nota')], max_length=8)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('oportunidad', models.ForeignKey(db_column='oportunidad_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='gestiones', to='comercial.oportunidad')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oportunidad_gestiones_por_usuario_id', to='plataforma.usuario')),
            ],
            options={
                'db_table': 'oportunidad_gestiones',
            },
        ),
    ]
