# Generated by Django 6.0.8 on 2026-09-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_initial'),
        ('plataforma', '0003_alter_informeguardado_correo_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadOfertaVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateField(blank=True, null=True)),
                ('documento_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('indice_indexacion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_indexacion_base', models.CharField(blank=True, max_length=7, null=True)),
                ('que_cambio', models.TextField(blank=True, null=True)),
                ('creado_por_usuario', models.ForeignKey(blank=True, db_column='creado_por_usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oferta_versiones_creadas', to='plataforma.usuario')),
                ('oferta', models.ForeignKey(db_column='oferta_id', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='comercial.oportunidadoferta')),
            ],
            options={
                'db_table': 'oportunidad_oferta_versiones',
                'unique_together': {('oferta', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='OportunidadOfertaVersionPrecio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='comercial.oportunidadofertaversion')),
            ],
            options={
                'db_table': 'oportunidad_oferta_version_precios',
                'unique_together': {('version', 'anio')},
            },
        ),
    ]
