# Generated by Django 6.0.8 on 2026-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_versiones_de_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadgestion',
            name='direccion',
            field=models.CharField(blank=True, choices=[('saliente', 'saliente'), ('entrante', 'entrante')], max_length=9, null=True),
        ),
    ]
